### ISSUE TITLE
History table pagination

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/liquidity-mining-dapp#114]
Stream history table pagination doesn't work well because it doesn't have the total number of items. It is available in `balance` entity as `allocationCount` field.

Also, as a suggestion, it would be better to hide pagination buttons when all the stream items can be shown in only one page. Situation like this
![image](https://user-images.githubusercontent.com/5684607/148239851-844ff5ec-fe6a-45cb-b9a8-726af52289fd.png)

**Comment by laurenluz** [comment]
Testing on staging.

It seems that they are hidden when there is only 1 entry on staging. I think this is good!

When there is more than 1, pagination shows up.
