### ISSUE TITLE
Zero APR on 100% GIV

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/liquidity-mining-dapp#127]
Happens when user refresh farming page

![image](https://user-images.githubusercontent.com/5684607/148699303-4b306c36-0466-4aa8-9769-5e36eb8a5769.png)

**Comment by laurenluz** [comment]
seems to be working right on staging and production

![image](https://user-images.githubusercontent.com/75490971/151074781-1a4bc340-100e-4d25-8779-9cda16c39789.png)
