### ISSUE TITLE
Add RegenFarms section to giv.giveth.io/givfarm

### ISSUE THREAD

**Issue by willyogo** [Giveth/liquidity-mining-dapp#173]
As a user, I want to be able to earn farming rewards for staking tokens for other projects.

[Mockup](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4453%3A110905)

1. A new section is added to the GIVfarm titled RegenFarms
2. Subtitle: Explore top projects changing the world and earn rewards for staking liquidity. [Learn more.](https://medium.com/giveth/farm-to-table-yields-with-decentralized-philanthropy-a5d71d28ef0d)

(note: use copy above, not copy in the mockup)
![image](https://user-images.githubusercontent.com/26232238/154138238-4f09221c-7edd-4729-9ca0-0777483bbe35.png)

**Comment by MohammadPCh** [comment]
> @MohammadPCh can you help improve the frontend on this?

@laurenluz I Implemented it in this pr : 
- #183
