### ISSUE TITLE
Add RegenStreams section to https://giv.giveth.io/givstream

### ISSUE THREAD

**Issue by willyogo** [Giveth/liquidity-mining-dapp#176]
1. A new section is added to the GIVstream titled RegenStreams, and the sections of the Streams page are rearranged according to the mockup
2. Subtitle: When you harvest farming rewards from the RegenFarms, a portion of the rewards is added to a RegenStream. Each stream flows continuously until its respective end date. [[Learn more.](https://giveth.io/placeholder-for-a-link-to-a-blog-post)](https://giveth.io/placeholder-for-a-link-to-a-blog-post)

[Mockup](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4453%3A110956)

**Comment by aminlatifi** [comment]
It's almost done in #183, just styling doesn't match with mock.

**Comment by MohammadPCh** [comment]
> @MohammadPCh Can you help with this one?

@laurenluz I Implemented it in this pr : 
- #183

**Comment by aminlatifi** [comment]
To test use preview link available in https://github.com/Giveth/liquidity-mining-dapp/pull/183

**Comment by divine-comedian** [comment]
title and subtitle has been updated

**Comment by laurenluz** [comment]
It is showing up, but... is there a reason the Fox stream is duplicated? I think this is a bug... I'm testing on PR #183 

@MohammadPCh @aminlatifi 

![image](https://user-images.githubusercontent.com/75490971/158503214-3ef32099-590f-4b29-a3df-3c854c1cf140.png)

**Comment by aminlatifi** [comment]
@laurenluz it,s based on design

**Comment by laurenluz** [comment]
@aminlatifi @MohammadPCh please remove the top redundant section as per our GIVeconomy call

so it shoudl just have this one:
![image](https://user-images.githubusercontent.com/75490971/158611159-b13fc25c-def6-41cb-893a-82872494f61e.png)

**Comment by divine-comedian** [comment]
testing on https://giveth-dapps-v2.vercel.app/givstream

![image](https://user-images.githubusercontent.com/67759413/158812474-c25f256e-99c7-4dad-8818-051a291b3bae.png)

appears to be only one FOXstream now .. 

A related question though - similar to the issue of showing the farming card when on a different network - currently the stream is completely hidden when we are not on Gnosis Chain - should we show the stream regardless of the network and on the harvest card prompt the user to switch to {eligible network}?

**Comment by laurenluz** [comment]
@markoprljic would love your opinion here on mitch's question

**Comment by markoprljic** [comment]
Similar answer to mention issue. 
Cc @mosaeedi
