### ISSUE TITLE
Define some guidelines around what qualifies a project for RegenFarms

### ISSUE THREAD

**Issue by willyogo** [Giveth/liquidity-mining-dapp#180]
Draft language detailing some boundaries around what qualifies (or disqualifies) a project from RegenFarms.

Consider including boundaries like whether or not a project has a social impact, tokenomics q's like total liquidity or total value of rewards, whether a project's token contract is audited, etc.

AC:
1. Publish language at or before RegenFarms announcement either in forum, announcement post, and/or docs

**Comment by laurenluz** [comment]
We discussed this briefly as:
- impact DAOs, DAOs that have positive externalities
- Min $5M market cap
- Min $100k rewards

**Comment by laurenluz** [comment]
From GIVeconomy call:
Griff: should design requirements around projects we want involved: TEC. Panvala

Need to be regen economy: need to be supporting some public good
could put up to a snapshot vote
