### ISSUE TITLE
Change Tooltip on Univ3 APR

### ISSUE THREAD

**Issue by laurenluz** [Giveth/liquidity-mining-dapp#181]
As per our sync call today, let's keep the gift heart emoji (not display just the min APR) and change the tooltip to say:

"Provide a narrow range of liquidity to maximize your rate of reward. The average APR is [AVG%], and the minimum APR for full range liquidity is [MIN%]."

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/cb054bb8-f66e-4dac-abc1-e54c56b6d133)

@aminlatifi

**Comment by aminlatifi** [comment]
@laurenluz It's implemented by PR https://github.com/Giveth/liquidity-mining-dapp/pull/172
Please confirm it works as expected by preview link

**Comment by laurenluz** [comment]
Working great! thanks @aminlatifi
