### ISSUE TITLE
RegenFarms - RegenStream is showing twice on GIVstream page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/liquidity-mining-dapp#193]
PR #183 

The RegenStream is showing double on the GIVstream page - 

![image](https://user-images.githubusercontent.com/67759413/158184359-4c61bfa2-ff5a-447a-9639-27676209aa92.png)

the one outlined in red should be removed I think.

**Comment by aminlatifi** [comment]
> PR #183
> 
> The RegenStream is showing double on the GIVstream page -
> 
> ![image](https://user-images.githubusercontent.com/67759413/158184359-4c61bfa2-ff5a-447a-9639-27676209aa92.png)
> 
> the one outlined in red should be removed I think.

It's according to design
