### ISSUE TITLE
RegenFarms - APR is shown but I am not getting rewards 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/liquidity-mining-dapp#194]
Pr #183 

I aped into the FOX/HNY RegenFarm with my test tokens - I'm not receiving any rewards and nothing is being shown on the Stream either - however we can see that the Multiverse bar is expanding

![image](https://user-images.githubusercontent.com/67759413/158193884-6a0140a9-7955-4dd2-9fd6-2d54a51fd880.png)
![image](https://user-images.githubusercontent.com/67759413/158194009-af22427f-5e74-4aab-9754-2226233b4d03.png)

not having rewards makes it impossible to test the harvest modal and harvest functionality

**Comment by aminlatifi** [comment]
That was because the reward duration (2 weeks) was over and no tx had happened after. Therefore `rewardRate` value was not updated. I notified unipool to pay another round of rewards. It should  be positive now

**Comment by divine-comedian** [comment]
Rewards are flowing - 
testing on https://giveth-dapps-v2.vercel.app/givfarm

![image](https://user-images.githubusercontent.com/67759413/158811467-149638ca-363a-44fe-85d7-a126a31f1883.png)

Issue seems to be resolved!
