### ISSUE TITLE
Add "mock" card to Regen Farms w CTA to "add your DAO"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/liquidity-mining-dapp#199]
As Giveth, I want other DAOs to participate in Regen Farms.
As a DAO participant, I want to know how my DAO can get a Regen Farm too.

We need design for this CTA. My suggestion is to create a "mock" card with a Regen Farm & Regen Stream. Something that says "Your DAO? Read about the requirements for becoming a Regen Farm."

The "read" text will be a link to the Regen farms requirements in our documentation (to be written).

@mosaeedi @markoprljic can you help with a quick mockup of this? I think it would be good if there was a card below regen farms with this CTA.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/ea7740d6-6647-4844-8ba8-ab3b1912ccc2)

**Comment by laurenluz** [comment]
This should come after Giveth/giveth-dapps-v2#366

**Comment by markoprljic** [comment]
I suggest outlined secondary button.

**Comment by laurenluz** [comment]
@mosaeedi are you working on this?

**Comment by laurenluz** [comment]
@mosaeedi Added this to the other issue by accident:

> ![Screen Shot 2022-03-21 at 1 31 34 PM](https://user-images.githubusercontent.com/13708322/159263028-8eca09cb-6b91-4c0c-af6f-07e6e059235c.png) Added the CTA section
> 
> ### Figma
> [Link to Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4453%3A110905)

Since it is is not a card, we should change the text to say:

Title: "Add Your DAO"
Subtext: "Apply to kickstart a RegenFarm for your for-good DAO"
Button text: "Apply Now"
Button link: https://giveth.typeform.com/regenfarms

The link should open in a new tab.

@MohammadPCh can you take this one with my edits?

**Comment by laurenluz** [comment]
@MohammadPCh the text changes in my previous comment need to still be applied.

**Comment by MohammadPCh** [comment]
@laurenluz excuse me,
I implemented it with Figma content.

**Comment by laurenluz** [comment]
@MohammadPCh button link text "APPLY NOW" should be all caps, to be consistent with other buttons.

Otherwise, looks great!

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/160494355-0bc56e71-8398-4c6f-8553-0f4bb3ec5660.png)

**Comment by laurenluz** [comment]
Button text should be all caps @pkretzschmar
